version: 0.2
nodejs: 14
commands:
- npm install -g yarn
- yarn install -g typescript
- yarn install
commands:
- echo Nothing to do in the pre_build phase...
commands:
- echo Build started on `date`
- yarn run build
- yarn test
commands:
- echo Build completed on `date`
paths:
- 'node_modules/**/*'
files:
- '**/*'
name: yourBuildName-$(date +%Y-%m-%d)